# fly.toml app configuration file generated for tfgjaimefront on 2023-06-03T17:36:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tfgjaimefront"
primary_region = "mad"

[env]
  PORT = "8081" # add this

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0